In [66]:
import pandas as pd

py_df = pd.read_csv('data/py_repos.csv', usecols=['rank', 'username/repo_name'])

class A:
    pass
method_names = sorted(dir(A))

py_df = pd.DataFrame({'rank': range(len(method_names)), 'username/repo_name': method_names})

all_safetensor_keys = set(f'{row["rank"]}.{row["username/repo_name"]}' for _, row in py_df.iterrows())
all_safetensor_keys

{'0.__class__',
 '1.__delattr__',
 '10.__gt__',
 '11.__hash__',
 '12.__init__',
 '13.__init_subclass__',
 '14.__le__',
 '15.__lt__',
 '16.__module__',
 '17.__ne__',
 '18.__new__',
 '19.__reduce__',
 '2.__dict__',
 '20.__reduce_ex__',
 '21.__repr__',
 '22.__setattr__',
 '23.__sizeof__',
 '24.__str__',
 '25.__subclasshook__',
 '26.__weakref__',
 '3.__dir__',
 '4.__doc__',
 '5.__eq__',
 '6.__format__',
 '7.__ge__',
 '8.__getattribute__',
 '9.__getstate__'}

In [67]:
from pathlib import Path

df_genesis = pd.read_csv('data/genesis.csv')
py_df = pd.DataFrame({'rank': df_genesis[df_genesis['chapter'] == 1]['verse'], 'username/repo_name': df_genesis[df_genesis['chapter'] == 1]['text']})

all_safetensor_keys = set(f'{row["rank"]}.{row["username/repo_name"]}' for _, row in py_df.iterrows())
all_safetensor_keys

{'1.In the beginning when God created the heavens and the earth,',
 '10.God called the dry land Earth, and the waters that were gathered together he called Seas. And God saw that it was good.',
 '11.Then God said, "Let the earth put forth vegetation: plants yielding seed, and fruit trees of every kind on earth that bear fruit with the seed in it." And it was so.',
 '12.The earth brought forth vegetation: plants yielding seed of every kind, and trees of every kind bearing fruit with the seed in it. And God saw that it was good.',
 '13.And there was evening and there was morning, the third day.',
 '14.And God said, "Let there be lights in the dome of the sky to separate the day from the night; and let them be for signs and for seasons and for days and years,',
 '15.and let them be lights in the dome of the sky to give light upon the earth." And it was so.',
 '16.God made the two great lights - the greater light to rule the day and the lesser light to rule the night - and the stars.',
 '17.God set them in the dome of the sky to give light upon the earth,',
 '18.to rule over the day and over the night, and to separate the light from the darkness. And God saw that it was good.',
 '19.And there was evening and there was morning, the fourth day.',
 '2.the earth was a formless void and darkness covered the face of the deep, while a wind from God swept over the face of the waters.',
 '20.And God said, "Let the waters bring forth swarms of living creatures, and let birds fly above the earth across the dome of the sky."',
 '21.So God created the great sea monsters and every living creature that moves, of every kind, with which the waters swarm, and every winged bird of every kind. And God saw that it was good.',
 '22.God blessed them, saying, "Be fruitful and multiply and fill the waters in the seas, and let birds multiply on the earth."',
 '23.And there was evening and there was morning, the fifth day.',
 '24.And God said, "Let the earth bring forth living creatures of every kind: cattle and creeping things and wild animals of the earth of every kind." And it was so.',
 '25.God made the wild animals of the earth of every kind, and the cattle of every kind, and everything that creeps upon the ground of every kind. And God saw that it was good.',
 '26.Then God said, "Let us make humankind in our image, according to our likeness; and let them have dominion over the fish of the sea, and over the birds of the air, and over the cattle, and over all the wild animals of the earth, and over every creeping thing that creeps upon the earth."',
 '27.So God created humankind in his image, in the image of God he created them; male and female he created them.',
 '28.God blessed them, and God said to them, "Be fruitful and multiply, and fill the earth and subdue it; and have dominion over the fish of the sea and over the birds of the air and over every living thing that moves upon the earth."',
 '29.God said, "See, I have given you every plant yielding seed that is upon the face of all the earth, and every tree with seed in its fruit; you shall have them for food.',
 '3.Then God said, "Let there be light"; and there was light.',
 '30.And to every beast of the earth, and to every bird of the air, and to everything that creeps on the earth, everything that has the breath of life, I have given every green plant for food." And it was so.',
 '31.God saw everything that he had made, and indeed, it was very good. And there was evening and there was morning, the sixth day.',
 '4.And God saw that the light was good; and God separated the light from the darkness.',
 '5.God called the light Day, and the darkness he called Night. And there was evening and there was morning, the first day.',
 '6.And God said, "Let there be a dome in the midst of the waters, and let it separate the waters from the waters."',
 '7.So God made the dome and separated the waters that were under the dome from the waters that were above the dome. And it was so.',
 '8.God called the dome Sky. And there was evening and there was morning, the second day.',
 '9.And God said, "Let the waters under the sky be gathered together into one place, and let the dry land appear." And it was so.'}

In [68]:
from safetensors.torch import load_file
import polars as pl
from pathlib import Path
import torch


schema = [('expert', pl.Int8)]
for _, row in py_df.iterrows():
    repo = row["username/repo_name"]
    schema.append((f'{repo}.w1', pl.Float16))
    schema.append((f'{repo}.w3', pl.Float16))


layer_to_df: dict[int, pl.DataFrame] = {}

for layer in range(32):

    df = pl.DataFrame(schema=schema)
    layer_path = Path(f'output/genesis/layer={layer:02d}')

    for expert in range(8):
        repos_to_activations = {}
        expert_path = layer_path / f'expert={expert}'

        w1_path = expert_path / 'w=1.safetensors'
        w3_path = expert_path / 'w=3.safetensors'

        w1 = load_file(w1_path)
        w3 = load_file(w3_path)

        assert set(w1.keys()) == all_safetensor_keys, f"Repo missing in w=1 for expert {expert}"
        assert set(w3.keys()) == all_safetensor_keys, f"Repo missing in w=3 for expert {expert}"

        for _, row in py_df.iterrows():
            key = f'{row["rank"]}.{row["username/repo_name"]}'

            w1_activation = w1[key].cpu().to(torch.float16).numpy()
            assert w1_activation.shape == (14336,), f"Unexpected shape for {key} in w=1: {w1_activation.shape}"
            repos_to_activations[f'{row["username/repo_name"]}.w1'] = w1_activation


            w3_activation = w3[key].cpu().to(torch.float16).numpy()
            assert w3_activation.shape == (14336,), f"Unexpected shape for {key} in w=3: {w3_activation.shape}"
            repos_to_activations[f'{row["username/repo_name"]}.w3'] = w3_activation
        
        curr_expert_df = pl.DataFrame(repos_to_activations)
        curr_expert_df = curr_expert_df.with_columns(pl.lit(expert, dtype=pl.Int8).alias("expert"))
        curr_expert_df = curr_expert_df.select(pl.col(df.columns))


        df = pl.concat([df, curr_expert_df], how="vertical")
    
    layer_to_df[layer] = df

In [69]:
df = layer_to_df[16]

df_top_50_indices = df.drop('expert').select(
    pl.all().arg_sort(descending=True).head(10)
)

# df_top_50_indices = df.drop('expert').select(
#     pl.all().sort(descending=True).head(10)
# )

# df_top_50_indices
df_top_50_indices // 14336

shape: (10, 62)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ In the    ┆ In the    ┆ the earth ┆ the earth ┆ … ┆ And to    ┆ And to    ┆ God saw   ┆ God saw  │
│ beginning ┆ beginning ┆ was a     ┆ was a     ┆   ┆ every     ┆ every     ┆ everythin ┆ everythi │
│ when God  ┆ when God  ┆ formless  ┆ formless  ┆   ┆ beast of  ┆ beast of  ┆ g that he ┆ ng that  │
│ crea…     ┆ crea…     ┆ void …    ┆ void …    ┆   ┆ the eart… ┆ the eart… ┆ had…      ┆ he had…  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 5         ┆ 2         ┆ 5         ┆ 7         ┆ … ┆ 5         ┆ 7         ┆ 5         ┆ 7        │
│ 2         ┆ 4         ┆ 4         ┆ 2         ┆ … ┆ 1         ┆ 5         ┆ 5         ┆ 2        │
│ 2         ┆ 2         ┆ 5         ┆ 1         ┆ … ┆ 4         ┆ 1         ┆ 2         ┆ 1        │
│ 3         ┆ 5         ┆ 2         ┆ 5         ┆ … ┆ 6         ┆ 2         ┆ 2         ┆ 0        │
│ 4         ┆ 5         ┆ 6         ┆ 5         ┆ … ┆ 7         ┆ 5         ┆ 4         ┆ 4        │
│ 5         ┆ 5         ┆ 7         ┆ 5         ┆ … ┆ 2         ┆ 3         ┆ 3         ┆ 5        │
│ 0         ┆ 1         ┆ 2         ┆ 4         ┆ … ┆ 0         ┆ 5         ┆ 3         ┆ 5        │
│ 1         ┆ 7         ┆ 4         ┆ 0         ┆ … ┆ 5         ┆ 0         ┆ 2         ┆ 6        │
│ 5         ┆ 2         ┆ 0         ┆ 5         ┆ … ┆ 5         ┆ 6         ┆ 5         ┆ 5        │
│ 0         ┆ 5         ┆ 1         ┆ 6         ┆ … ┆ 2         ┆ 4         ┆ 6         ┆ 7        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [70]:
from pathlib import Path
import re

lines = Path('genesis.txt').read_text().splitlines()

chapter, verse, text = [], [], []
for line in lines:
    # [chapter:verse] text
    match = re.match(r'\[(\d+):(\d+)\] (.+)', line)
    if not match:
        raise ValueError(f"Line does not match expected format: {line}")
    chapter.append(int(match.group(1)))
    verse.append(int(match.group(2)))
    text.append(match.group(3))

df_genesis = pd.DataFrame({'chapter': chapter, 'verse': verse, 'text': text})
df_genesis.to_csv('genesis.csv', index=False)

In [71]:
pd.read_csv('data/genesis.csv')

      chapter  verse                                               text
0           1      1  In the beginning when God created the heavens ...
1           1      2  the earth was a formless void and darkness cov...
2           1      3  Then God said, "Let there be light"; and there...
3           1      4  And God saw that the light was good; and God s...
4           1      5  God called the light Day, and the darkness he ...
...       ...    ...                                                ...
1528       50     22  So Joseph remained in Egypt, he and his father...
1529       50     23  Joseph saw Ephraim's children of the third gen...
1530       50     24  Then Joseph said to his brothers, "I am about ...
1531       50     25  So Joseph made the Israelites swear, saying, "...
1532       50     26  And Joseph died, being one hundred ten years o...

[1533 rows x 3 columns]

In [82]:
# join to chapter and text
df_genesis = pd.read_csv('data/genesis.csv')
df_genesis_by_chapter = df_genesis.groupby('chapter').apply(lambda g: g.sort_values('verse')['text'].tolist())
df_genesis_by_chapter = df_genesis_by_chapter.apply(lambda verses: '\n'.join(verses))
df_genesis_by_chapter.to_frame(name='text').reset_index()

/tmp/ipykernel_119397/1620948220.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_genesis_by_chapter = df_genesis.groupby('chapter').apply(lambda g: g.sort_values('verse')['text'].tolist())

    chapter                                               text
0         1  In the beginning when God created the heavens ...
1         2  Thus the heavens and the earth were finished, ...
2         3  Now the serpent was more crafty than any other...
3         4  Now the man knew his wife Eve, and she conceiv...
4         5  This is the list of the descendants of Adam. W...
5         6  When people began to multiply on the face of t...
6         7  Then the LORD said to Noah, "Go into the ark, ...
7         8  But God remembered Noah and all the wild anima...
8         9  God blessed Noah and his sons, and said to the...
9        10  These are the descendants of Noah's sons, Shem...
10       11  Now the whole earth had one language and the s...
11       12  Now the LORD said to Abram, "Go from your coun...
12       13  So Abram went up from Egypt, he and his wife, ...
13       14  In the days of King Amraphel of Shinar, King A...
14       15  After these things the word of the LORD came t...
15       16  Now Sarai, Abram's wife, bore him no children....
16       17  When Abram was ninety-nine years old, the LORD...
17       18  The LORD appeared to Abraham by the oaks of Ma...
18       19  The two angels came to Sodom in the evening, a...
19       20  From there Abraham journeyed toward the region...
20       21  The LORD dealt with Sarah as he had said, and ...
21       22  After these things God tested Abraham. He said...
22       23  Sarah lived one hundred twenty-seven years; th...
23       24  Now Abraham was old, well advanced in years; a...
24       25  Abraham took another wife, whose name was Ketu...
25       26  Now there was a famine in the land, besides th...
26       27  When Isaac was old and his eyes were dim so th...
27       28  Then Isaac called Jacob and blessed him, and c...
28       29  Then Jacob went on his journey, and came to th...
29       30  When Rachel saw that she bore Jacob no childre...
30       31  Now Jacob heard that the sons of Laban were sa...
31       32  Jacob went on his way and the angels of God me...
32       33  Now Jacob looked up and saw Esau coming, and f...
33       34  Now Dinah the daughter of Leah, whom she had b...
34       35  God said to Jacob, "Arise, go up to Bethel, an...
35       36  These are the descendants of Esau (that is, Ed...
36       37  Jacob settled in the land where his father had...
37       38  It happened at that time that Judah went down ...
38       39  Now Joseph was taken down to Egypt, and Potiph...
39       40  Some time after this, the cupbearer of the kin...
40       41  After two whole years, Pharaoh dreamed that he...
41       42  When Jacob learned that there was grain in Egy...
42       43  Now the famine was severe in the land.\nAnd wh...
43       44  Then he commanded the steward of his house, "F...
44       45  Then Joseph could no longer control himself be...
45       46  When Israel set out on his journey with all th...
46       47  So Joseph went and told Pharaoh, "My father an...
47       48  After this Joseph was told, "Your father is il...
48       49  Then Jacob called his sons, and said: "Gather ...
49       50  Then Joseph threw himself on his father's face...